// Generated by Ignite ignite.com/cli

import { StdFee } from "@cosmjs/launchpad";
import { SigningStargateClient, DeliverTxResponse } from "@cosmjs/stargate";
import { EncodeObject, GeneratedType, OfflineSigner, Registry } from "@cosmjs/proto-signing";
import { msgTypes } from './registry';
import { IgniteClient } from "../client"
import { MissingWalletError } from "../helpers"
import { Api } from "./rest";
import { MsgReset } from "./types/sao/node/tx";
import { MsgRemoveVstorage } from "./types/sao/node/tx";
import { MsgAddVstorage } from "./types/sao/node/tx";
import { MsgClaimReward } from "./types/sao/node/tx";
import { MsgCreate } from "./types/sao/node/tx";


export { MsgReset, MsgRemoveVstorage, MsgAddVstorage, MsgClaimReward, MsgCreate };

type sendMsgResetParams = {
  value: MsgReset,
  fee?: StdFee,
  memo?: string
};

type sendMsgRemoveVstorageParams = {
  value: MsgRemoveVstorage,
  fee?: StdFee,
  memo?: string
};

type sendMsgAddVstorageParams = {
  value: MsgAddVstorage,
  fee?: StdFee,
  memo?: string
};

type sendMsgClaimRewardParams = {
  value: MsgClaimReward,
  fee?: StdFee,
  memo?: string
};

type sendMsgCreateParams = {
  value: MsgCreate,
  fee?: StdFee,
  memo?: string
};


type msgResetParams = {
  value: MsgReset,
};

type msgRemoveVstorageParams = {
  value: MsgRemoveVstorage,
};

type msgAddVstorageParams = {
  value: MsgAddVstorage,
};

type msgClaimRewardParams = {
  value: MsgClaimReward,
};

type msgCreateParams = {
  value: MsgCreate,
};


export const registry = new Registry(msgTypes);

const defaultFee = {
  amount: [],
  gas: "200000",
};

interface TxClientOptions {
  addr: string
	prefix: string
	signer?: OfflineSigner
}

export const txClient = ({ signer, prefix, addr }: TxClientOptions = { addr: "http://localhost:26657", prefix: "cosmos" }) => {

  return {
		
		async sendMsgReset({ value, fee, memo }: sendMsgResetParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgReset: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry, prefix});
				let msg = this.msgReset({ value: MsgReset.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgReset: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendMsgRemoveVstorage({ value, fee, memo }: sendMsgRemoveVstorageParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgRemoveVstorage: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry, prefix});
				let msg = this.msgRemoveVstorage({ value: MsgRemoveVstorage.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgRemoveVstorage: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendMsgAddVstorage({ value, fee, memo }: sendMsgAddVstorageParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgAddVstorage: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry, prefix});
				let msg = this.msgAddVstorage({ value: MsgAddVstorage.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgAddVstorage: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendMsgClaimReward({ value, fee, memo }: sendMsgClaimRewardParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgClaimReward: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry, prefix});
				let msg = this.msgClaimReward({ value: MsgClaimReward.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgClaimReward: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendMsgCreate({ value, fee, memo }: sendMsgCreateParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgCreate: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry, prefix});
				let msg = this.msgCreate({ value: MsgCreate.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgCreate: Could not broadcast Tx: '+ e.message)
			}
		},
		
		
		msgReset({ value }: msgResetParams): EncodeObject {
			try {
				return { typeUrl: "/saonetwork.sao.node.MsgReset", value: MsgReset.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgReset: Could not create message: ' + e.message)
			}
		},
		
		msgRemoveVstorage({ value }: msgRemoveVstorageParams): EncodeObject {
			try {
				return { typeUrl: "/saonetwork.sao.node.MsgRemoveVstorage", value: MsgRemoveVstorage.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgRemoveVstorage: Could not create message: ' + e.message)
			}
		},
		
		msgAddVstorage({ value }: msgAddVstorageParams): EncodeObject {
			try {
				return { typeUrl: "/saonetwork.sao.node.MsgAddVstorage", value: MsgAddVstorage.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgAddVstorage: Could not create message: ' + e.message)
			}
		},
		
		msgClaimReward({ value }: msgClaimRewardParams): EncodeObject {
			try {
				return { typeUrl: "/saonetwork.sao.node.MsgClaimReward", value: MsgClaimReward.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgClaimReward: Could not create message: ' + e.message)
			}
		},
		
		msgCreate({ value }: msgCreateParams): EncodeObject {
			try {
				return { typeUrl: "/saonetwork.sao.node.MsgCreate", value: MsgCreate.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgCreate: Could not create message: ' + e.message)
			}
		},
		
	}
};

interface QueryClientOptions {
  addr: string
}

export const queryClient = ({ addr: addr }: QueryClientOptions = { addr: "http://localhost:1317" }) => {
  return new Api({ baseURL: addr });
};

class SDKModule {
	public query: ReturnType<typeof queryClient>;
	public tx: ReturnType<typeof txClient>;
	
	public registry: Array<[string, GeneratedType]> = [];

	constructor(client: IgniteClient) {		
	
		this.query = queryClient({ addr: client.env.apiURL });		
		this.updateTX(client);
		client.on('signer-changed',(signer) => {			
		 this.updateTX(client);
		})
	}
	updateTX(client: IgniteClient) {
    const methods = txClient({
        signer: client.signer,
        addr: client.env.rpcURL,
        prefix: client.env.prefix ?? "cosmos",
    })
	
    this.tx = methods;
    for (let m in methods) {
        this.tx[m] = methods[m].bind(this.tx);
    }
	}
};

const Module = (test: IgniteClient) => {
	return {
		module: {
			SaonetworkSaoNode: new SDKModule(test)
		},
		registry: msgTypes
  }
}
export default Module;